-- MySQL Script generated by MySQL Workbench
-- 08/16/16 19:16:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_directorio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_directorio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_directorio` DEFAULT CHARACTER SET utf8 ;
USE `db_directorio` ;

-- -----------------------------------------------------
-- Table `db_directorio`.`tipo_contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_directorio`.`tipo_contacto` (
  `id_tipo_contacto` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `estado` BIT NULL,
  PRIMARY KEY (`id_tipo_contacto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_directorio`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_directorio`.`contacto` (
  `id_contacto` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(150) NOT NULL,
  `telefono` VARCHAR(25) NULL,
  `id_tipo_contacto` BIGINT NOT NULL,
  PRIMARY KEY (`id_contacto`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  INDEX `fk_contacto_tipo_contacto_idx` (`id_tipo_contacto` ASC),
  CONSTRAINT `fk_contacto_tipo_contacto`
    FOREIGN KEY (`id_tipo_contacto`)
    REFERENCES `db_directorio`.`tipo_contacto` (`id_tipo_contacto`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
